version: '3.9'

services:
  dagster:
    build: .
    container_name: dagster
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
    command: dagster dev -f dagster_pipeline/repository.py -h 0.0.0.0 -p 3000
    networks:
      - dagster_net

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dagster_net

volumes:
  pgdata:

networks:
  dagster_net:
    driver: bridge
